services:
  # 后端服务 - 简化版 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.simple
    container_name: semgrep-playground-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # 前端服务 - 超级简化版
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.simple
    container_name: semgrep-playground-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    name: semgrep-playground-demo